extra debugging utils

diff --git a/.github/workflows/release-exchange.yml b/.github/workflows/release-exchange.yml
--- a/.github/workflows/release-exchange.yml
+++ b/.github/workflows/release-exchange.yml
@@ -468,11 +468,27 @@ jobs:
         run: |
           sudo apt-get update && sudo apt-get install -y unzip
 
+      - name: Verify Unzip Installation
+        continue-on-error: true
+        run: |
+          if ! command -v unzip > /dev/null; then
+            echo "Error: unzip is not installed."
+            exit 1
+          fi
+
+      - name: Validate Zip File
+        continue-on-error: true
+        run: |
+          if ! unzip -tq ${{github.workspace}}/${{matrix.exchange.id}}_${{ needs.builds.outputs.APP_VERSION }}_ubuntu-22.04-x64.zip; then
+            echo "Error: The zip file is corrupted or invalid."
+            exit 1
+          fi
+
       - name: Run create-latest-json.sh
         shell: bash
         run: |
-          sudo bash ./scripts/create-latest-json.sh "${{ needs.builds.outputs.APP_VERSION }}" "${{matrix.exchange.id}}" --verbose
-          ls -la "${{ github.workspace }}"
+          set -x
+          sudo bash ./scripts/create-latest-json.sh "${{ needs.builds.outputs.APP_VERSION }}" "${{matrix.exchange.id}}"
 
       - name: Upload msi artifact
         id: upload-msi
